adjusting pipeline, trouble shooting ssh issue

diff --git a/.github/workflows/deploy-ci.yml b/.github/workflows/deploy-ci.yml
--- a/.github/workflows/deploy-ci.yml
+++ b/.github/workflows/deploy-ci.yml
@@ -29,12 +29,21 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
 
+      - name: Write SSH key to file
+        run: |
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
+          chmod 400 key.pem
+
+      - name: Check SSH access
+        run: |
+          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo SSH connection successful" || { echo 'SSH failed'; exit 1; }
+
       - name: SSH into EC2 and deploy
         uses: appleboy/ssh-action@v0.1.4
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          key: key.pem
           script: |
             docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce_prod_app:latest
             docker stop ecommerce_prod_app || true
